.pylintrc, pcs_vuln_container_locations.py
Clear pylint checks that do not surface locally
Buy time to identify why these checks surface in guthub but not locally
Manually
=> disable some lint checks, fix others

.pylintrc, pc_lib/pc_lib_utility.py, pcs_images_packages_read.py, pcs_vuln_container_locations.py
refactor image search, using it to add a registry search
simplify code
simplify usage
manual
=> Add registry search

.pylintrc, pcs_images_packages_read.py, pcs_vuln_container_locations.py
correct an indexerror
found an indexerror
manual
=> Correct exceptions

pc_lib/pc_lib_api.py, pc_lib/posture/_extended.py, pcs_compliance_export.py, pcs_policy_custom_export.py, pcs_resources_export.py
allow for the configuration of concurrency with threaded API calls
avoid API rate limiting
manually, pylint
=> Configure concurrency

pc_lib/posture/_endpoints.py
add endpoints for licensing, add a test script to call those endpoints
allow organizations to report on licensing by cloud account group, often correlated to business unit
manual
=> add endpoints for licensing, add test script to call those endpoints

pc_lib/pc_lib_utility.py, pcs_configure.py
reconcile changes from None to ''
manual
=> normalize None and empty and use single quotes

README.md, pcs_policy_set_status.py
add cloud type and policy severity params, move all policy selection to its own param
customer request
=> additional policy criteria

pcs_configure.py, pcs_script_example.py
Remove test print
debugging
functional and pylint
=> Remove test print

pcs_account_groups_by_tags.py
=> Initial revision of automating account group assignment by tags

pc_lib/compute/_audits.py, pcs_compute_logs.py
poc audit data collector
customer use case with saas
manual, pylint
=> poc audit data collector

pc_lib/compute/_audits.py, pcs_compute_logs.py
=> break out console history, improve ui

README.md, pcs_compute_forward_to_siem.py, pcs_compute_logs.py
Add multithreading for API calls
Add overlapping so as to not miss entries
Renamed and documented
manual, pylint
=> Threading and overlap

pc_lib/compute/_registry.py, pc_lib/compute/_status.py, pcs_compute_forward_to_siem.py
provides a view of the current state of the registries
convert the equivalent shell script
pylint, manual
=> provides a view of the current state of the registries

pcs_defender_report_by_cloud_account.py
basic defender counting
customer ask
manual pylint
=> basic defender counting

pc_lib/compute/__init__.py, pc_lib/compute/_audits.py, pc_lib/compute/_defenders.py, pc_lib/compute/_logs.py
add defender and system log endpoints, move console log endpoint
additional endpoints
pylint
=> add defender and system log endpoints, move console log endpoint

.pylintrc, pcs_ssl_configure.py
use simpler import, ignore pylint socket errors specific to brew
=> use simpler import, ignore pylint socket errors specific to brew

pc_lib/compute/_images.py, pcs_container_vulnerabilities_read.py, pcs_images_packages_read.py, pcs_vuln_container_locations.py
allow specifying of query_params for images_list_read
do not limit the images_list_read method
manual, pylint
=> allow specifying of query_params for images_list_read

pc_lib/compute/_containers.py, pc_lib/compute/_images.py, pcs_vuln_container_locations.py
=> extend query_params to containers_list_read

scripts/pcs_rotate_service_account_access_key.py
add rotate/tumble key script
SA request feature
pylint and manual 
=> add rotate/tumble key script

README.md, scripts/pcs_rotate_service_account_access_key.py
=> update documentation and address sorting

scripts/pcs_alerts_read.py
add -fpn and --policyname filter
New filter
tested on SESandBox
=> add -fpn and --policyname filter

pc_lib/code_security/__init__.py, pc_lib/code_security/_errors.py, pc_lib/code_security/_fixes.py, pc_lib/code_security/_repositories.py, pc_lib/code_security/_scans.py, pc_lib/code_security/_suppressions.py, pc_lib/code_security/code_security.py, pc_lib/compute/__init__.py, pc_lib/compute/compute.py, pc_lib/pc_lib_api.py, pc_lib/posture/__init__.py, pc_lib/posture/posture.py
add code security apis
new apis
manual and pylint
=> add code security apis

pc_lib/code_security/_errors.py, pc_lib/code_security/code_security.py, pc_lib/compute/compute.py, scripts/pcs_cs_errors_for_file.py, scripts/pcs_cs_repositories_read.py
=> Example code security

pc_lib/code_security/code_security.py, pc_lib/compute/compute.py, pc_lib/posture/_endpoints.py, pc_lib/posture/posture.py, scripts/pcs_alerts_read.py
add pagination for CSPM, update for CWPP and PCCS
support pagination for v2/alerts
manual, pylint
=> Pagination

pc_lib/code_security/code_security.py, pc_lib/compute/compute.py, pc_lib/pc_lib_api.py, pc_lib/pc_lib_utility.py, pc_lib/posture/posture.py, scripts/pcs_container_vulnerabilities_read.py
add a global debugging command line parameter
simplify debugging
manual, pylint
=> add a global debugging command line parameter

prismacloud/api/pc_lib_api.py
avoid writing error.log unless errors
avoid writing error.log unless errors
manual
=> avoid writing error.log unless errors

scripts/examples/README.md, scripts/examples/pcs_vuln_container_with_cve_2022_22965.py
List packages that contain CVE-2022-22965 and JDK **other than** 1.8.  The results are stored to a *CVE-2022-22965-WITHOUT-JAVA8.csv* in the same folder
- [x ] All new and existing tests passed.
=> example for CVE-2022-22965

scripts/examples/pcs_vuln_container_with_cve_2022_22965.py
added validation to ensure dict key is present before accessing it
=> added validation to ensure dict key is present before accessing it

tests/unit.py
poc unit test
Mock the APIs and test the code!
```
python3 tests/unit.py
```
=> poc unit test

README.md, prismacloud/api/compute/compute.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/README.md
correct compute extend
correct compute extend
pylint
=> correct compute extend

prismacloud/api/posture/_endpoints.py
Add enterprise and anomaly settings into CSPM endpoint.
I would like to use those endpoint for the prisma cloud cli
Pylint
=> Add enterprise and anomaly settings into CSPM endpoint.

prismacloud/api/version.py
=> Release 4.0.6

prismacloud/api/posture/_endpoints.py, scripts/pcs_apis_ingested.py
=> query cloud provider apis ingested via suggest

scripts/pcs_compute_container_observed_connections.py
add collections and improve param handling
user feedback
=> add collections and improve param handling

prismacloud/api/version.py
=> Version 4.0.8

README.md, scripts/examples/README.md, setup.py
The repo is now less of a collection of scripts and more of and SDK with scripts.
Renaming to match the Python package it is published as.
N/A
=> prepare to rename this repo

prismacloud/api/compute/_tags.py
add compute tags endpoints
provide methods for these endpoints
manual, pylint
=> add compute tags endpoints

prismacloud/api/compute/__init__.py, prismacloud/api/version.py
=> include tags and rev version

scripts/pcs_cloud_discovery_defense_stats.py
=> Adds cloud discovery stats export

prismacloud/api/compute/_settings.py
I want to give the possibility to Prisma Cloud customer to automate their host auto deploy rules.
We need automation when we have a high number of cloud accounts
- [ x] I have read the **CONTRIBUTING** document.
=> add host auto deploy rules

prismacloud/api/compute/_logs.py
=> add agentless endpoint

prismacloud/api/compute/__init__.py, prismacloud/api/compute/_hosts.py, scripts/pcs_hosts_vulnerabilities_read.py
add hosts endpoints
customer identified 
=>  add hosts endpoints

scripts/pcs_apis_ingested.py, scripts/pcs_compute_container_observed_connections.py
fix indenting and trailing
field reported indent issues
pylint
=> indenting and trailing

.github/workflows/pylint.yml, .github/workflows/pypi.yml, .pylintrc, prismacloud/api/compute/_logs.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/pcs_images_packages_read.py
refactor pylinting
missed files
pylint, manual
=> pylint redux

prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py
improve response handling
json.loads() should not return None
=> improve response handling

prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/pc_lib_api.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/pcs_container_vulnerabilities_on_running_hosts.py
refactor to reduce size, increase readability 
the execute methods are complex
pylint manual
- Maintenance
=> improve executes

prismacloud/api/compute/__init__.py, prismacloud/api/version.py
Add Collections Endpoints
customer request 
pylint
=> Add Collections

prismacloud/api/compute/_policies.py, scripts/pcs_images_packages_read.py
add policies and fix exact match
bugs
manual, pylint
=> add policies and fix exact match

.pylintrc, prismacloud/api/code_security/code_security.py, prismacloud/api/compute/_collections.py, prismacloud/api/compute/compute.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/pcs_user_import.py
allow empty response
always check for cvs
some endpoints return no content
pylint, manual
=> allow empty response

scripts/pcs_cloud_discovery_defense_stats.py
=> Adds detailed EKS statistics

prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/pc_lib_api.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py
use exponential retries on recoverable errors
copied from better code
manual, pylint
=> exponential retries

scripts/pcs_outdated_defenders.py
Adds script to enumerate deployed defenders with outdated versions
=> Adds pcs_outdated_defenders.py

prismacloud/api/compute/_settings.py
add serverless auto deploy rules
Automate the serverless autodeploy rules
=> add serverless auto deploy rules

README.md, prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/pc_lib_api.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/README.md
Add China to autoconfigure.
China URLs end in a different suffix.
pylint, manual
=> Add China to autoconfigure

README.md, prismacloud/api/pc_lib_api.py, prismacloud/api/version.py, scripts/pcs_ssl_configure.py
update verify param and correct api sanitation
bugs
manual, pylint
=>  update verify param and correct api sanitation

scripts/examples/pcs_vuln_container_with_cve_2022_22965.py, scripts/pc_account_add_example_standalone.py, scripts/pc_compute_cloud_discovery_example_standalone.py, scripts/pcs_cloud_discovery_defense_stats.py, scripts/pcs_compute_forward_to_siem.py, scripts/pcs_outdated_defenders.py
newer pylint newer issues
newer pylint newer issues
pylint
=> newer pylint

prismacloud/api/posture/_endpoints.py, prismacloud/api/version.py
Add license API v2 since v1 is deprecated
api v1 is deprecated
=> Add license API v2 since v1 is deprecated

prismacloud/api/compute/_defenders.py, prismacloud/api/version.py
Add the feature to list defenders
Add the feature to list defenders
=> Add defender list

prismacloud/api/code_security/code_security.py, prismacloud/api/compute/_audits.py, prismacloud/api/compute/compute.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/pcs_compute_forward_to_siem.py
none is okay
allow empty responses
=> none is okay

prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py, scripts/pcs_agentless_logs.py
Handle gzip responses
Handle agentless logs
manul, pylint
=> Gzip and download

prismacloud/api/compute/_defenders.py
Added pagination capability to api/v1/defenders endpoint.
Giving incorrect information if more than 50 defenders.
Tested against onprem and saas compute tenants.
=> Added pagination to defenders endpoint

prismacloud/api/pc_lib_utility.py, scripts/pcs_account_groups_by_tags.py, scripts/pcs_compute_container_observed_connections.py, scripts/pcs_outdated_defenders.py, scripts/pcs_policy_set_status.py
Avoid param collision
Param collision
Manual pylint
=> Cleanup params

prismacloud/api/compute/_audits.py, prismacloud/api/compute/_logs.py, prismacloud/api/version.py, scripts/pcs_agentless_logs.py, scripts/pcs_forensics_download.py
add forensics download and cleanup
undocumented apis
manual, pylint
=> Forensics and downloads

prismacloud/api/pc_lib_utility.py
restore the config script
ux
manual, pylint
=> any script can save config, but this makes it better

prismacloud/api/pc_lib_api.py, prismacloud/api/pc_lib_utility.py, prismacloud/api/version.py, scripts/pcs_configure.py
fix verify setting, and do not use cspm url to identify compute url when configuring
fix verify setting, and do not use cspm url to identify compute url when configuring
avoid errors
manual
=> fix verify setting

prismacloud/api/__init__.py, prismacloud/api/code_security/code_security.py, prismacloud/api/compute/compute.py, prismacloud/api/pc_lib_api.py, prismacloud/api/pc_lib_utility.py, prismacloud/api/posture/posture.py, prismacloud/api/version.py
raise instead of sys.exit
python best practice
manual and pylint
=> raise instead of sys.exit

prismacloud/api/code_security/_errors.py, prismacloud/api/version.py
add query_params to errors_list_last_authors
=> add query_params to errors_list_last_authors

prismacloud/api/version.py
=> bump to 5.1.3

prismacloud/api/code_security/_suppressions.py, prismacloud/api/version.py
add query params to suppressions_justifications_list_read
=>  add query params to suppressions_justifications_list_read

prismacloud/api/posture/_endpoints.py, prismacloud/api/version.py
=> add iam rql queries

prismacloud/api/posture/_endpoints.py, prismacloud/api/version.py
change the limit to get 1000 results
=> change the limit to get 1000 results

prismacloud/api/cwpp/__init__.py, prismacloud/api/cwpp/_feeds.py
add undocumented feeds endpoints
help customers with usage
manually, pylint
=> add undocumented feeds endpoints

scripts/pcs_usage.py
=> make the cloud_account_group_name required

scripts/pcs_usage.py
=> output account names

scripts/pcs_account_groups_by_tags.py
=> Poc of group by tag

scripts/pcs_images_packages_read.py
=> Adds binaries and applications support

scripts/pcs_images_packages_read.py
=> fix exact_match_name

scripts/pcs_ssl_configure.py
allow users to specify subjects
handle other intercepting proxies
manual, pylint
=> allow users to specify subjects

scripts/pcs_compute_forward_to_siem.py
add audit type filter, and verbose mode
aid testing
manual and pylint
=> add audit type filter, and verbose mode

scripts/README.md
=> add conf file format docs

scripts/pcs_policy_set_status.py
Add filters for subtype, descriptor, label, mode in the set_status script. 
This will help with more granular controls on enabling and disabling policies.
=> Add filters for subtype,descriptor,label,mode

scripts/pcs_outdated_defenders.py
=> Update defender script

scripts/pcs_defender_report_by_cloud_account.py
=> Update to use defenders_list_read

scripts/pcs_outdated_defenders.py
=> connected and summary flags

prismacloud/api/pccs/__init__.py, prismacloud/api/pccs/_fixes.py, prismacloud/api/pccs/_packages.py, prismacloud/api/version.py
=> Add fixes for CVEs

scripts/pcs_container_csp.py
=> Add container and CSP

prismacloud/api/cspm/_endpoints.py, prismacloud/api/version.py
Add POST method for the `/v2/inventory` to add filters options.
=> add asset_inventory_list_read_post function

prismacloud/api/pc_lib_api.py, prismacloud/api/version.py
Fix hard coded print line of user agent
It's not something we want. :-)
=> Fix hard coded print line

.gitignore, prismacloud/api/cwpp/_cloud.py, prismacloud/api/version.py
=> remove trailing query

.github/workflows/pypi.yml, prismacloud/api/cspm/_endpoints.py, prismacloud/api/version.py
add source_to_granter and granter_to_dest for IAM Search
=> add source_to_granter and granter_to_dest for IAM Search

scripts/pcs_rotate_service_account_access_key.py
Update class attribute for equality checks
Pre-fix the script errors out with "AttributeError: 'PrismaCloudAPI' object has no attribute 'username'.
I created temporary service account keys in app3 pcs tenant and ran the script post-fix. Script now worked as expected.
=> update class attribute
